### PR TITLE
Allow users to create a service file at a default location

### LINKED ISSUE #27: Feature Request: Create new file
If no file exists, it would be great to automatically create one at the default location.

### PR DESCRIPTION
**Pull request by gacarrillor**
Useful to help them to get started with the plugin if no service file is found when opening the dialog.

https://github.com/opengisch/qgis-pg-service-parser-plugin/assets/652785/7f6dae90-b9ec-430a-b7b8-dce61e0b34df

Fix #27

### CODE REVIEW

**Comment by gacarrillor** [comment]
Note this PR points to https://github.com/opengisch/qgis-pg-service-parser-plugin/tree/add_remove_service_settings branch.
When we consider the current PR ready, I'd suggest that we merge it before merging PR #31 to master.

**Comment by 3nids** [comment]
Awesome!

Do you know why highlighting when modified doesn't work in the demo?

**Review by 3nids — APPROVED** [review]

**Comment by gacarrillor** [comment]
> Awesome!
> 
> Do you know why highlighting when modified doesn't work in the demo?

Host/port/dbname are actually stored in the newly created file, as a 'template'. That's why they don't appear in green.
If this can lead to some confusion, I can try to add them as if they were being edited instead.

**Comment by gacarrillor** [comment]
> Do you know why highlighting when modified doesn't work in the demo?

Much better ideed! Thanks for the suggestion!

image

**Pull request merged**
